services:
  wohnee-be:
    image: wohnee-be
    container_name: wohnee-be
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - wohnee-net

networks:
  wohnee-net:
    driver: bridge
